version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "9002:6379"
    volumes:
      - ./redis_data:/data
    environment:
      - TZ=Asia/Shanghai
      - REDIS_PASSWORD=lvhj123456
    command: ["redis-server", "--requirepass", "lvhj123456"]

volumes:
  redis_data:
    driver: bridge