# notification-manager-operator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: notification-manager
    meta.helm.sh/release-namespace: kubesphere-monitoring-system
  creationTimestamp: "2024-07-13T03:38:34Z"
  generation: 3
  labels:
    app.kubernetes.io/managed-by: Helm
    control-plane: controller-manager
  name: notification-manager-operator
  namespace: kubesphere-monitoring-system
  resourceVersion: "6331"
  uid: de983ed4-98d0-455e-bc0f-6f863226d9b1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        control-plane: controller-manager
    spec:
      affinity: {}
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: registry.cn-hangzhou.aliyuncs.com/whatever233/kubesphere-kube-rbac-proxy:v0.11.0
          imagePullPolicy: IfNotPresent
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 5m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - args:
            - --metrics-addr=127.0.0.1:8080
            - --enable-leader-election
          command:
            - /notification-manager-operator
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: registry.cn-hangzhou.aliyuncs.com/whatever233/notification-manager-operator:v2.3.0
          imagePullPolicy: IfNotPresent
          name: notification-manager-operator
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 5m
              memory: 20Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
            - mountPath: /etc/localtime
              name: host-time
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: notification-manager-sa
      serviceAccountName: notification-manager-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: notification-manager-webhook-server-cert
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-time
